# main text of home
name: Eleni "Lena" Metheniti
bio: A cartesian 3-dimensional monkey with a passion for computational morphology.

# twitter summary info
description: >
    PhD Candidate at CNRS Occitanie Ouest
    Previously: Universität des Saarlandes, DFKI

picture: assets/images/profile.JPG

url: http://lenakmeth.github.io
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
twitter: lenakmeth
# google: mygoogle
instagram: lenakmeth
# pinterest: mypinterest
linkedin: lenakmeth
# youtube: myyoutube
# spotify: myspotify
github: lenakmeth
#email: firstname . lastname @ dfki.com
cv: assets/cv.pdf

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
